version: '3'
services:
  pg-database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    container_name: pg-database
    # volumes:
    #   - ./docker/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - skynet
networks:
  skynet:
    driver: bridge